version = 1

[[targets]]
triple = "aarch64-apple-darwin"
archive = "tar.gz"
runner = "macos-15"

[[targets]]
triple = "x86_64-unknown-linux-gnu"
archive = "tar.gz"
runner = "ubuntu-24.04"

[[targets]]
triple = "x86_64-pc-windows-msvc"
archive = "zip"
runner = "windows-2025"
